version: '3.8'

services:
  boxing-game:
    build: .
    ports:
      - "8080:8080"
    container_name: ultimate-boxing-game
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
